# Generated by Django 4.1.6 on 2023-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='long_bio',
            field=models.TextField(default='long bio', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.CharField(default='short bio', max_length=100),
        ),
    ]
