# Generated by Django 4.2 on 2023-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_long_bio_profile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='Influencer', max_length=100),
        ),
    ]
